import Menu from "@/components/Menu"
import Rodape from "@/components/Rodape"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Menu/>
        {children}</body>
        <Rodape/>
    </html>
  )
}
